export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_LOGIN_STATE_TO_TRUE = 'SET_LOGIN_STATE_TO_TRUE';
export const SET_LOGIN_STATE_TO_FALSE = 'SET_LOGIN_STATE_TO_FALSE';


export const SET_CONNECTION_ID = 'SET_CONNECTION_ID'


export const SET_PRODUCT_REQUESTED_ID = 'SET_PRODUCT_REQUESTED_ID'